### ISSUE TITLE
fail , crash on win11 

### ISSUE THREAD

**Issue by classstudios** [OpenRA/TiberianDawnHD#31]
OpenRA engine version 4f880f6269
cnc mod version playtest-20241116
Date: 2024-12-08 11:30:49Z
Operating System: Windows (X64, Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 6.0.36
Installed Language: zh (Installed) zh (Current) zh (Current UI)
Exception of type `System.IO.FileNotFoundException`: File not found: temperat.pal
   at OpenRA.FileSystem.FileSystem.Open(String filename)
   at OpenRA.Mods.Common.Traits.PaletteFromFileInfo.OpenRA.Traits.IProvidesCursorPaletteInfo.ReadPalette(IReadOnlyFileSystem fileSystem)
   at OpenRA.Graphics.CursorProvider.<>c__DisplayClass2_0.<.ctor>b__4(String p)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at OpenRA.Graphics.CursorProvider..ctor(ModData modData)
   at OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)

**Comment by pchote** [comment]
Is this using Steam for the Remaster contents, or Origin?
